config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'users#index'

end

app/models/authentication.rb
 class Authentication < ActiveRecord::Base

     belongs_to :user

      def self.create_with_omniauth(auth_hash)
        create! do |auth|
          auth.provider = auth_hash["provider"]
          auth.uid = auth_hash["uid"]
          auth.token = auth_hash["credentials"]["token"]
        end
      end

      def update_token(auth_hash)
        self.token = auth_hash["credentials"]["token"]
        self.save
      end

    end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  require'securerandom'
  has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["first_name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = SecureRandom.hex(6)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  # def password_optional?
  #   true
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

      def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]

        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
        if authentication.user
          user = authentication.user 
          authentication.update_token(auth_hash)
          @next = root_url
          @notice = "Signed in!"
        else
          user = User.create_with_auth_and_hash(authentication,auth_hash)
          @next = edit_user_path(user)   
          @notice = "User created - confirm or edit details..."
        end
        sign_in(user)
        redirect_to @next, :notice => @notice
      end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users =User.all
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pair BnB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

<%= yield %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js">
  </script>

</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<a href="/auth/facebook">
 <i class="fa fa-facebook"/>
 Log In with Facebook
</a>	

app/views/users/index.html.erb
<div class="thumbnail">
  <h1>WELCOME HOME</h3>
  <h2>Rent unique places to stay from local hosts in 190+ countries.</h4>
  <div class="overlay">
  </div>
  <video autoplay loop="loop" preload="auto" class="photo">
    <source src="//a0.muscache.com/airbnb/static/London-P1-1.mp4" type='video/mp4'>
    <source src="//a0.muscache.com/airbnb/static/London-P1-0.webm" type='video/webm'>
  </video>
  <!--<div class="photo">-->
  </div>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>